version: '3.8'

services:
  nginx:
      build: ./nginx/local
      volumes:
          - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 90:90
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: always
    ports:
     - 8080:8080
     - 28015:28015
     - 29015:29015
    command:
      - /bin/bash
      - -c
      - rethinkdb --bind all
    volumes:
      - rethinkdb_prod_data:/data
volumes:
  rethinkdb_prod_data:
