version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: always
    ports:
     - 8080:8080
     - 28015:28015
     - 29015:29015
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb --bind all
    volumes:
      - rethinkdb_prod_data:/data
  api:
      build:
          context: ./api
      depends_on:
            - rethinkdb
      environment:
        - RETHINKDB=rethinkdb
      ports:
          - 8888:8000
      volumes:
          - ./api:/code
  client:
      build:
          context: ./client
      depends_on:
            - rethinkdb
            - api
      ports:
          - 3333:3000
  nginx:
      build: ./nginx/prod
      depends_on:
        - api
        - client
      volumes:
          - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      ports:
          - 90:90
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.162.40.0/24
volumes:
  rethinkdb_prod_data:

